name: Build

on:
  push:
    branches:
      - "**"

env:
  GO_VERSION: '1.21'

jobs:
  build:
    name: Run checks and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Use ONLY setup-go's built-in caching (recommended approach)
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true  # Let setup-go handle caching automatically

      - name: Download dependencies
        run: go mod download

      - name: Vet
        run: make vet

      - name: Test
        run: make test

      - name: Build
        run: make

  format:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Check formatting
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "::error::Unformatted files found:"
            echo "$unformatted" | while read -r line; do
              echo "::error file=$line::File needs formatting"
            done
            exit 1
          fi
