name: Test on all platforms

on:
  pull_request:
    # this will allow the tests to be run on demand
  workflow_dispatch:

env:
  GO_VERSION: "1.22.1"  # Using stable version

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Sync dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        run: go test -v ./...